package com.sinema;

import javax.swing.ImageIcon;

/**
 *
 * @author Muratcan Öksüm & Emir Tuncer
 */
public class AnaSayfa extends javax.swing.JFrame {

    VeritabaniIslemler islemler = new VeritabaniIslemler();

    /**
     * Creates new form AnaSayfa
     */
    public AnaSayfa() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        bilet_al_panel = new javax.swing.JPanel();
        bilet_al = new javax.swing.JLabel();
        bilet_kontrol_panel = new javax.swing.JPanel();
        bilet_kontrol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        yetkili_giris = new javax.swing.JMenuItem();
        cikis = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sinema Otomasyonu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon("./src/com/sinema/images/icon.png").getImage());
        setLocation(new java.awt.Point(500, 150));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/sinema_giris.png"))); // NOI18N

        bilet_al_panel.setBackground(new java.awt.Color(160, 160, 160));
        bilet_al_panel.setForeground(new java.awt.Color(255, 255, 255));
        bilet_al_panel.setToolTipText("");

        bilet_al.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bilet_al.setForeground(new java.awt.Color(255, 255, 255));
        bilet_al.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bilet_al.setText("BİLET AL");
        bilet_al.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bilet_alMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bilet_alMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bilet_alMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bilet_al_panelLayout = new javax.swing.GroupLayout(bilet_al_panel);
        bilet_al_panel.setLayout(bilet_al_panelLayout);
        bilet_al_panelLayout.setHorizontalGroup(
            bilet_al_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bilet_al_panelLayout.createSequentialGroup()
                .addComponent(bilet_al, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        bilet_al_panelLayout.setVerticalGroup(
            bilet_al_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bilet_al_panelLayout.createSequentialGroup()
                .addComponent(bilet_al, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bilet_kontrol_panel.setBackground(new java.awt.Color(160, 160, 160));

        bilet_kontrol.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bilet_kontrol.setForeground(new java.awt.Color(255, 255, 255));
        bilet_kontrol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bilet_kontrol.setText("BİLET KONTROL");
        bilet_kontrol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bilet_kontrolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bilet_kontrolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bilet_kontrolMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bilet_kontrol_panelLayout = new javax.swing.GroupLayout(bilet_kontrol_panel);
        bilet_kontrol_panel.setLayout(bilet_kontrol_panelLayout);
        bilet_kontrol_panelLayout.setHorizontalGroup(
            bilet_kontrol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bilet_kontrol_panelLayout.createSequentialGroup()
                .addComponent(bilet_kontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bilet_kontrol_panelLayout.setVerticalGroup(
            bilet_kontrol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bilet_kontrol_panelLayout.createSequentialGroup()
                .addComponent(bilet_kontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bilet_al_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bilet_kontrol_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bilet_kontrol_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilet_al_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71)
                .addComponent(bilet_al_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bilet_kontrol_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        jMenu1.setText("Seçenekler");

        yetkili_giris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/yetkili.png"))); // NOI18N
        yetkili_giris.setText("Yetkili Giriş");
        yetkili_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yetkili_girisActionPerformed(evt);
            }
        });
        jMenu1.add(yetkili_giris);
        yetkili_giris.getAccessibleContext().setAccessibleDescription("");

        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/exit.png"))); // NOI18N
        cikis.setText("Çıkış");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        jMenu1.add(cikis);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    Ana sayfa penceresini kapatıp. YetkiliGiriş class'ını çağırır ve penceresini görünür yapar.

    private void yetkili_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yetkili_girisActionPerformed
        this.setVisible(false);
        YetkiliGiris yetkig = new YetkiliGiris();
        yetkig.setVisible(true);
    }//GEN-LAST:event_yetkili_girisActionPerformed

//    Çıkış seçeneği seçildiğinde uygulamadan çıkış yapar.

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cikisActionPerformed

//    Bİlet al butonu efekti.

    private void bilet_alMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_alMouseEntered
        bilet_al_panel.setBackground(new java.awt.Color(96, 96, 96));
    }//GEN-LAST:event_bilet_alMouseEntered

//    Bİlet al butonu efekti.

    private void bilet_alMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_alMouseExited
        bilet_al_panel.setBackground(new java.awt.Color(160, 160, 160));
    }//GEN-LAST:event_bilet_alMouseExited

//    Bİlet al butonu efekti.
    
    private void bilet_kontrolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_kontrolMouseEntered
        bilet_kontrol_panel.setBackground(new java.awt.Color(96, 96, 96));
    }//GEN-LAST:event_bilet_kontrolMouseEntered

//    Bİlet al butonu efekti.

    private void bilet_kontrolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_kontrolMouseExited
        bilet_kontrol_panel.setBackground(new java.awt.Color(160, 160, 160));
    }//GEN-LAST:event_bilet_kontrolMouseExited

//    Ana sayfa peneceresini kapatır. Ardından biletal classını çağırıp penceresini açar.
    
    private void bilet_alMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_alMouseClicked
        this.setVisible(false);
        BiletAl blt = new BiletAl();
        blt.setVisible(true);
    }//GEN-LAST:event_bilet_alMouseClicked

//    Ana sayfa peneceresini kapatır. Ardından biletkontrol classını çağırıp penceresini açar.
    
    private void bilet_kontrolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_kontrolMouseClicked
        this.setVisible(false);
        BiletKontrol blt = new BiletKontrol();
        blt.setVisible(true);    }//GEN-LAST:event_bilet_kontrolMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bilet_al;
    private javax.swing.JPanel bilet_al_panel;
    private javax.swing.JLabel bilet_kontrol;
    private javax.swing.JPanel bilet_kontrol_panel;
    private javax.swing.JMenuItem cikis;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem yetkili_giris;
    // End of variables declaration//GEN-END:variables
}
