package com.sinema;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Muratcan Öksüm & Emir Tuncer
 */
public class BiletOnay extends javax.swing.JFrame {

    VeritabaniIslemler islemler = new VeritabaniIslemler();
    BiletAl bltalq = new BiletAl();
    KoltukSecim klt = new KoltukSecim();
    private String filmadi = bltalq.filmadi_gonder;
    private int secilenkoltukadet = klt.secilenbilet_gonder;
    private int toplamtutar = klt.totaltutar_gonder;
    private String koltuklar_gelen = klt.biletleri_gonder;
    private String filmtarih = bltalq.filmtarih_gonder;
    private String filmsaat = bltalq.filmsaat_gonder;
    private String filmsalon = bltalq.filmsalon_gonder;

    /**
     * Creates new form Fatura
     */
    public BiletOnay() {
        initComponents();
        secilen_biletler.setText(koltuklar_gelen);
        total_tutar.setText(String.valueOf(toplamtutar) + " TL");
        filmadi_t.setText(filmadi);
        sean_tarih.setText(filmtarih);
        seans_saat.setText(filmsaat);
        seans_salon.setText(filmsalon);
        hata.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onay_b = new javax.swing.JButton();
        geri_b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        secilen_biletler = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ad_gir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tc_gir = new javax.swing.JTextField();
        soyad_gir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        total_tutar = new javax.swing.JTextField();
        seans_saat = new javax.swing.JTextField();
        sean_tarih = new javax.swing.JTextField();
        filmadi_t = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        seans_salon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hata = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Bilet Onay");
        setIconImage(new ImageIcon("./src/com/sinema/images/icon.png").getImage());
        setLocation(new java.awt.Point(500, 150));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        onay_b.setText("Onayla");
        onay_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onay_bActionPerformed(evt);
            }
        });

        geri_b.setText("Geri");
        geri_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_bActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AKTİF BİLET");

        jLabel2.setText("Seçtiğiniz Koltuklar :");

        secilen_biletler.setEditable(false);

        jLabel3.setText("Adınız :");

        jLabel4.setText("Soyadınız :");

        jLabel5.setText("TC Kimlik No :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ÖDEME İŞLEMİ SALON GİRİŞİNDEDİR !");

        jLabel7.setText("Toplam Tutar :");

        total_tutar.setEditable(false);

        seans_saat.setEditable(false);

        sean_tarih.setEditable(false);

        filmadi_t.setEditable(false);

        jLabel8.setText("Film Adı :");

        jLabel9.setText("Seans Tarihi :");

        jLabel10.setText("Seans Saati :");

        seans_salon.setEditable(false);

        jLabel11.setText("Salon :");

        hata.setForeground(new java.awt.Color(255, 0, 0));
        hata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hata.setText("123");

        jMenu1.setText("Seçenekler");

        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/exit.png"))); // NOI18N
        cikis.setText("Çıkış");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        jMenu1.add(cikis);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(geri_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(onay_b)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seans_salon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(secilen_biletler, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ad_gir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(soyad_gir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tc_gir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(filmadi_t, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sean_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(seans_saat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(0, 19, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(hata, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(secilen_biletler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soyad_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tc_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmadi_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sean_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seans_saat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seans_salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(hata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geri_b)
                    .addComponent(onay_b))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_cikisActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        AnaSayfa ansyf = new AnaSayfa();
        ansyf.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void geri_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_bActionPerformed
        this.setVisible(false);
        KoltukSecim klt = new KoltukSecim();
        klt.setVisible(true);
    }//GEN-LAST:event_geri_bActionPerformed

    // kullanıcadan istenilen verileri alır ve boş olup olmadığını kontrol ederek geribildirim verir.
    // kontrol başarılı olur ise bileti girilen bilgilere göre kullanıcaya tanımlar ve veritabanında saklar.
    
    private void onay_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onay_bActionPerformed
        if (ad_gir.getText().trim().equals("")) {
            hata.setText("Adınız kısımı boş olamaz!");
        } else if (soyad_gir.getText().trim().equals("")) {
            hata.setText("Soyadınız kısımı boş olamaz!");
        } else if (tc_gir.getText().trim().equals("")) {
            hata.setText("TC No kısımı boş olamaz!");
        } else if (biletadetKontrol()) {
            hata.setText("");
            koltuklariSec();
            biletBilgiCikar();
            this.setVisible(false);
            AnaSayfa ansyf = new AnaSayfa();
            ansyf.setVisible(true);
            JOptionPane.showMessageDialog(null, "Biletiniz başarıyla oluşturulmuştur !", "Bilet Yönetim", 1);
        } else {
            hata.setText("Daha önce adınıza bilet tanımlanmış!");
        }

    }//GEN-LAST:event_onay_bActionPerformed

    
    // Aynı verilere sahip ikinci bir bilet oluşturulmaması için kontrol sağlar.
    
    public boolean biletadetKontrol() {
        String isim = ad_gir.getText().trim();
        String soyisim = soyad_gir.getText().trim();
        String tcno = tc_gir.getText().trim();

        ArrayList<Bilet> biletler = new ArrayList<Bilet>();
        biletler = islemler.biletGetir();
        if (biletler != null) {

            for (Bilet bilet : biletler) {
                String biletisim = bilet.getAd().trim();
                String biletsoyisim = bilet.getSoyad().trim();
                String bilettc = bilet.getTcno().trim();

                if (biletisim.equals(isim) && biletsoyisim.equals(soyisim)
                        && bilettc.equals(tcno)) {;
                    return false;
                } else {
                    return true;
                }
            }

        }
        return true;

    }

    // kullanıcın seçtiği ve girdiği verileri veritabanına aktarır.
    
    public void biletBilgiCikar() {
        String ad = ad_gir.getText();
        String soyad = soyad_gir.getText();
        String tcno = tc_gir.getText();
        String koltuklar = koltuklar_gelen;
        String film_adi = filmadi;
        String film_tarih = filmtarih;
        String film_saat = filmsaat;
        String film_salon = filmsalon;
        int tutar = toplamtutar;
        islemler.biletEkle(ad, soyad, tcno, koltuklar, tutar, film_adi, film_tarih, film_saat, film_salon);
    }

    // kullanının seçtiği koltuk adetine göre koltuk bilgilerini veritabanına işleyip koltuğun doluluk durumunu düzenler.
    
    public void koltuklariSec() {
        String koltuk = null, koltuk1 = null, koltuk2 = null, koltuk3 = null;
        if (secilenkoltukadet == 1) {
            koltuk = koltuklar_gelen.trim();
            islemler.koltukGuncelle(filmadi, koltuk, filmsalon, filmtarih, filmsaat, "true");
        } else if (secilenkoltukadet == 2) {
            koltuklar_gelen.trim();
            koltuk = koltuklar_gelen.substring(0, 2);
            koltuk1 = koltuklar_gelen.substring(3);
            islemler.koltukGuncelle(filmadi, koltuk, filmsalon, filmtarih, filmsaat, "true");
            islemler.koltukGuncelle(filmadi, koltuk1, filmsalon, filmtarih, filmsaat, "true");

        } else if (secilenkoltukadet == 3) {
            koltuklar_gelen.trim();
            koltuk = koltuklar_gelen.substring(0, 2);
            koltuk1 = koltuklar_gelen.substring(3, 5);
            koltuk2 = koltuklar_gelen.substring(6);
            islemler.koltukGuncelle(filmadi, koltuk, filmsalon, filmtarih, filmsaat, "true");
            islemler.koltukGuncelle(filmadi, koltuk1, filmsalon, filmtarih, filmsaat, "true");
            islemler.koltukGuncelle(filmadi, koltuk2, filmsalon, filmtarih, filmsaat, "true");
        } else if (secilenkoltukadet == 4) {
            koltuklar_gelen.trim();
            koltuk = koltuklar_gelen.substring(0, 2);
            koltuk1 = koltuklar_gelen.substring(3, 5);
            koltuk2 = koltuklar_gelen.substring(6, 8);
            koltuk3 = koltuklar_gelen.substring(9);
            islemler.koltukGuncelle(filmadi, koltuk, filmsalon, filmtarih, filmsaat, "true");
            islemler.koltukGuncelle(filmadi, koltuk1, filmsalon, filmtarih, filmsaat, "true");
            islemler.koltukGuncelle(filmadi, koltuk2, filmsalon, filmtarih, filmsaat, "true");
            islemler.koltukGuncelle(filmadi, koltuk3, filmsalon, filmtarih, filmsaat, "true");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiletOnay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiletOnay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiletOnay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiletOnay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiletOnay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_gir;
    private javax.swing.JMenuItem cikis;
    private javax.swing.JTextField filmadi_t;
    private javax.swing.JButton geri_b;
    private javax.swing.JLabel hata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton onay_b;
    private javax.swing.JTextField sean_tarih;
    private javax.swing.JTextField seans_saat;
    private javax.swing.JTextField seans_salon;
    private javax.swing.JTextField secilen_biletler;
    private javax.swing.JTextField soyad_gir;
    private javax.swing.JTextField tc_gir;
    private javax.swing.JTextField total_tutar;
    // End of variables declaration//GEN-END:variables
}
