package com.sinema;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Muratcan Öksüm & Emir Tuncer
 */
public class BiletKontrol extends javax.swing.JFrame {

    VeritabaniIslemler islemler = new VeritabaniIslemler();

    /**
     * Creates new form BiletKontrol
     */
    public BiletKontrol() {
        initComponents();
        ImageIcon icon = new ImageIcon("./src/com/sinema/images/icon.png");
        this.setIconImage(icon.getImage());
        hata.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biletkontroltext = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        isim_gir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tc_gir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        soyisim_gir = new javax.swing.JTextField();
        kontrolButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        film_adi = new javax.swing.JTextField();
        film_tarih = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        film_saat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        film_salon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        film_koltuklar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        film_tutar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hata = new javax.swing.JLabel();
        kontrolButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Bilet Kontrol");
        setIconImage(new ImageIcon("./src/com/sinema/images/icon.png").getImage());
        setLocation(new java.awt.Point(500, 150));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        biletkontroltext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        biletkontroltext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biletkontroltext.setText("BİLET KONTROL");

        jLabel1.setText("Adınız :");

        isim_gir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isim_girActionPerformed(evt);
            }
        });

        jLabel2.setText("Soyadınız :");

        jLabel3.setText("TC Kimlik No:");

        soyisim_gir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyisim_girActionPerformed(evt);
            }
        });

        kontrolButton.setText("Kontrol");
        kontrolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontrolButtonActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Film Adı :");

        film_adi.setEditable(false);
        film_adi.setEnabled(false);

        film_tarih.setEditable(false);
        film_tarih.setEnabled(false);

        jLabel5.setText("Tarih :");

        film_saat.setEditable(false);
        film_saat.setEnabled(false);

        jLabel6.setText("Saat :");

        film_salon.setEditable(false);
        film_salon.setEnabled(false);

        jLabel7.setText("Salon :");

        film_koltuklar.setEditable(false);
        film_koltuklar.setEnabled(false);

        jLabel8.setText("Koltuklar :");

        film_tutar.setEditable(false);
        film_tutar.setEnabled(false);

        jLabel9.setText("Tutar :");

        hata.setForeground(new java.awt.Color(255, 0, 0));
        hata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hata.setText("jLabel10");

        kontrolButton1.setText("Sıfırla");
        kontrolButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontrolButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Seçenekler");

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/exit.png"))); // NOI18N
        exit.setText("Çıkış");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biletkontroltext, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(isim_gir)
                                            .addComponent(tc_gir)
                                            .addComponent(soyisim_gir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kontrolButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(kontrolButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5)
                                .addComponent(film_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(film_koltuklar)
                                    .addComponent(film_salon)
                                    .addComponent(film_tarih)
                                    .addComponent(film_saat)
                                    .addComponent(film_tutar))))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biletkontroltext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(film_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(film_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(film_saat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(film_salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(film_koltuklar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(film_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(isim_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(soyisim_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tc_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kontrolButton)
                            .addComponent(kontrolButton1))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);    }//GEN-LAST:event_exitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        AnaSayfa ans = new AnaSayfa();
        ans.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void isim_girActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isim_girActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isim_girActionPerformed

    private void soyisim_girActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyisim_girActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyisim_girActionPerformed

    private void kontrolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontrolButtonActionPerformed
        if (isim_gir.getText().trim().equals("")) {
            hata.setText("Adınız kısımı boş olamaz!");
        } else if (soyisim_gir.getText().trim().equals("")) {
            hata.setText("Soyadınız kısımı boş olamaz!");
        } else if (tc_gir.getText().trim().equals("")) {
            hata.setText("TC No kısımı boş olamaz!");
        } else {
            bilgileriGetir();
        }
    }//GEN-LAST:event_kontrolButtonActionPerformed

    private void kontrolButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontrolButton1ActionPerformed
        film_adi.setText("");
        film_tarih.setText("");
        film_koltuklar.setText("");
        film_saat.setText("");
        film_salon.setText("");
        film_tutar.setText("");
        hata.setText("");
        isim_gir.setText("");
        soyisim_gir.setText("");
        tc_gir.setText("");

        //DİSABLED
        film_adi.setEnabled(false);
        film_tarih.setEnabled(false);
        film_koltuklar.setEnabled(false);
        film_saat.setEnabled(false);
        film_salon.setEnabled(false);
        film_tutar.setEnabled(false);


    }//GEN-LAST:event_kontrolButton1ActionPerformed

    public void bilgileriGetir() {
        String isim = isim_gir.getText().trim();
        String soyisim = soyisim_gir.getText().trim();
        String tcno = tc_gir.getText().trim();

        ArrayList<Bilet> biletler = new ArrayList<Bilet>();
        biletler = islemler.biletGetir();
        int biletsayisi = 0;
        if (biletler != null) {

            for (Bilet bilet : biletler) {
                String biletisim = bilet.getAd().trim();
                String biletsoyisim = bilet.getSoyad().trim();
                String bilettc = bilet.getTcno().trim();

                if (biletisim.equals(isim) && biletsoyisim.equals(soyisim)
                        && bilettc.equals(tcno)) {;
                    film_adi.setText(bilet.getFilmadi());
                    film_tarih.setText(bilet.getFilmtarih());
                    film_koltuklar.setText(bilet.getKoltuklar());
                    film_saat.setText(bilet.getFilmsaat());
                    film_salon.setText(bilet.getFilmsalon());
                    film_tutar.setText(String.valueOf(bilet.getTutar()) + " TL");

                    // Enabled
                    film_adi.setEnabled(true);
                    film_tarih.setEnabled(true);
                    film_koltuklar.setEnabled(true);
                    film_saat.setEnabled(true);
                    film_salon.setEnabled(true);
                    film_tutar.setEnabled(true);
                    hata.setText("");
                    break;
                } else {
                    hata.setText("Girdiğiniz bilgiler ile eşleşen bilet bulunmadı !");

                }
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiletKontrol.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiletKontrol.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiletKontrol.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiletKontrol.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiletKontrol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biletkontroltext;
    private javax.swing.JMenuItem exit;
    private javax.swing.JTextField film_adi;
    private javax.swing.JTextField film_koltuklar;
    private javax.swing.JTextField film_saat;
    private javax.swing.JTextField film_salon;
    private javax.swing.JTextField film_tarih;
    private javax.swing.JTextField film_tutar;
    private javax.swing.JLabel hata;
    private javax.swing.JTextField isim_gir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton kontrolButton;
    private javax.swing.JButton kontrolButton1;
    private javax.swing.JTextField soyisim_gir;
    private javax.swing.JTextField tc_gir;
    // End of variables declaration//GEN-END:variables
}
