package com.sinema;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muratcan Öksüm & Emir Tuncer
 */
public class KoltukSecim extends javax.swing.JFrame {

    VeritabaniIslemler islemler = new VeritabaniIslemler();
    BiletAl bltalq = new BiletAl();
    private int biletUcret = 55;
    private String filmadi = bltalq.filmadi_gonder;
    private String filmtarih = bltalq.filmtarih_gonder;
    private String filmsaat = bltalq.filmsaat_gonder;
    private String filmsalon = bltalq.filmsalon_gonder;
    public static int totaltutar_gonder;
    public static int secilenbilet_gonder;
    public static String biletleri_gonder;

    /**
     * Creates new form KoltukSecim
     */
    public KoltukSecim() {
        initComponents();
        doluYerler(filmadi);
        hata.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Koltuk1 = new javax.swing.JLabel();
        Koltuk2 = new javax.swing.JLabel();
        Koltuk3 = new javax.swing.JLabel();
        Koltuk4 = new javax.swing.JLabel();
        Koltuk5 = new javax.swing.JLabel();
        Koltuk6 = new javax.swing.JLabel();
        Koltuk7 = new javax.swing.JLabel();
        Koltuk8 = new javax.swing.JLabel();
        Koltuk9 = new javax.swing.JLabel();
        Koltuk10 = new javax.swing.JLabel();
        Koltuk11 = new javax.swing.JLabel();
        Koltuk12 = new javax.swing.JLabel();
        Koltuk13 = new javax.swing.JLabel();
        Koltuk14 = new javax.swing.JLabel();
        Koltuk15 = new javax.swing.JLabel();
        Koltuk16 = new javax.swing.JLabel();
        Koltuk17 = new javax.swing.JLabel();
        Koltuk18 = new javax.swing.JLabel();
        Koltuk19 = new javax.swing.JLabel();
        Koltuk20 = new javax.swing.JLabel();
        Koltuk21 = new javax.swing.JLabel();
        Koltuk22 = new javax.swing.JLabel();
        Koltuk23 = new javax.swing.JLabel();
        Koltuk24 = new javax.swing.JLabel();
        Koltuk25 = new javax.swing.JLabel();
        secim1 = new javax.swing.JCheckBox();
        secim3 = new javax.swing.JCheckBox();
        secim2 = new javax.swing.JCheckBox();
        secim4 = new javax.swing.JCheckBox();
        secim6 = new javax.swing.JCheckBox();
        secim5 = new javax.swing.JCheckBox();
        secim8 = new javax.swing.JCheckBox();
        secim9 = new javax.swing.JCheckBox();
        secim7 = new javax.swing.JCheckBox();
        secim10 = new javax.swing.JCheckBox();
        secim11 = new javax.swing.JCheckBox();
        secim12 = new javax.swing.JCheckBox();
        secim14 = new javax.swing.JCheckBox();
        secim16 = new javax.swing.JCheckBox();
        secim13 = new javax.swing.JCheckBox();
        secim15 = new javax.swing.JCheckBox();
        secim17 = new javax.swing.JCheckBox();
        secim19 = new javax.swing.JCheckBox();
        secim18 = new javax.swing.JCheckBox();
        secim20 = new javax.swing.JCheckBox();
        secim22 = new javax.swing.JCheckBox();
        secim21 = new javax.swing.JCheckBox();
        secim23 = new javax.swing.JCheckBox();
        secim24 = new javax.swing.JCheckBox();
        secim25 = new javax.swing.JCheckBox();
        satır_A = new javax.swing.JLabel();
        satır_B = new javax.swing.JLabel();
        satır_C = new javax.swing.JLabel();
        satır_D = new javax.swing.JLabel();
        satır_E = new javax.swing.JLabel();
        sutun_1 = new javax.swing.JLabel();
        sutun_2 = new javax.swing.JLabel();
        sutun_3 = new javax.swing.JLabel();
        sutun_4 = new javax.swing.JLabel();
        sutun_5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        secililer_listesi = new javax.swing.JTextField();
        onayla_but = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        toplam_tutar = new javax.swing.JTextField();
        hata = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Koltuk Seçimi");
        setIconImage(new ImageIcon("./src/com/sinema/images/icon.png").getImage());
        setLocation(new java.awt.Point(500, 150));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Koltuk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        Koltuk25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/chair36px.png"))); // NOI18N

        secim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim1ActionPerformed(evt);
            }
        });

        secim3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim3ActionPerformed(evt);
            }
        });

        secim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim2ActionPerformed(evt);
            }
        });

        secim4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim4ActionPerformed(evt);
            }
        });

        secim6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim6ActionPerformed(evt);
            }
        });

        secim5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim5ActionPerformed(evt);
            }
        });

        secim8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim8ActionPerformed(evt);
            }
        });

        secim9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim9ActionPerformed(evt);
            }
        });

        secim7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim7ActionPerformed(evt);
            }
        });

        secim10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim10ActionPerformed(evt);
            }
        });

        secim11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim11ActionPerformed(evt);
            }
        });

        secim12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim12ActionPerformed(evt);
            }
        });

        secim14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim14ActionPerformed(evt);
            }
        });

        secim16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim16ActionPerformed(evt);
            }
        });

        secim13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim13ActionPerformed(evt);
            }
        });

        secim15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim15ActionPerformed(evt);
            }
        });

        secim17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim17ActionPerformed(evt);
            }
        });

        secim19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim19ActionPerformed(evt);
            }
        });

        secim18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim18ActionPerformed(evt);
            }
        });

        secim20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim20ActionPerformed(evt);
            }
        });

        secim22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim22ActionPerformed(evt);
            }
        });

        secim21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim21ActionPerformed(evt);
            }
        });

        secim23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim23ActionPerformed(evt);
            }
        });

        secim24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim24ActionPerformed(evt);
            }
        });

        secim25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim25ActionPerformed(evt);
            }
        });

        satır_A.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        satır_A.setText("A");

        satır_B.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        satır_B.setText("B");

        satır_C.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        satır_C.setText("C");

        satır_D.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        satır_D.setText("D");

        satır_E.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        satır_E.setText("E");

        sutun_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sutun_1.setText("1");

        sutun_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sutun_2.setText("2");

        sutun_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sutun_3.setText("3");

        sutun_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sutun_4.setText("4");

        sutun_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sutun_5.setText("5");

        jLabel1.setText("Seçilen Koltuklar:");

        secililer_listesi.setEditable(false);

        onayla_but.setText("Onayla");
        onayla_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onayla_butActionPerformed(evt);
            }
        });

        jLabel2.setText("Toplam Tutar:");

        toplam_tutar.setEditable(false);

        hata.setForeground(new java.awt.Color(204, 0, 51));
        hata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hata.setText("En fazla 4 bilet alınabilir!");

        jMenu1.setText("Seçenekler");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/exit.png"))); // NOI18N
        jMenuItem1.setText("Çıkış");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(satır_B, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(satır_C, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(satır_D, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(satır_E, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(satır_A, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secim1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Koltuk4)
                            .addComponent(Koltuk9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Koltuk22)
                                .addComponent(Koltuk10)
                                .addComponent(Koltuk15)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(secim16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secim21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(secim6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secim2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Koltuk3)
                            .addComponent(Koltuk8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Koltuk23)
                                .addComponent(Koltuk6)
                                .addComponent(Koltuk13)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(secim12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secim17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secim22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(secim7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(secim11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(sutun_1)
                        .addGap(74, 74, 74)
                        .addComponent(sutun_2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Koltuk2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Koltuk5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Koltuk24)
                                        .addComponent(Koltuk19)
                                        .addComponent(Koltuk14)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(secim13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(secim18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(secim23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(secim3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secim8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Koltuk25)
                                    .addComponent(Koltuk20)
                                    .addComponent(Koltuk11)
                                    .addComponent(Koltuk16)
                                    .addComponent(Koltuk12)
                                    .addComponent(secim4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secim9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secim24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(secim14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secim19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Koltuk1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Koltuk17)
                                    .addComponent(Koltuk7))
                                .addComponent(Koltuk21)
                                .addComponent(Koltuk18)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(secim20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secim25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(secim10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secim5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(secim15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(sutun_3)
                        .addGap(68, 68, 68)
                        .addComponent(sutun_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sutun_5)
                        .addGap(14, 14, 14)))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(secililer_listesi, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onayla_but)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toplam_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hata, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sutun_1)
                        .addComponent(sutun_2))
                    .addComponent(sutun_3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sutun_4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sutun_5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Koltuk5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secim3)
                        .addGap(14, 14, 14)
                        .addComponent(Koltuk2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secim8)
                        .addGap(14, 14, 14)
                        .addComponent(Koltuk24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secim13)
                        .addGap(15, 15, 15)
                        .addComponent(Koltuk19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secim18)
                        .addGap(13, 13, 13)
                        .addComponent(Koltuk14))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Koltuk7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(secim5)
                            .addGap(14, 14, 14)
                            .addComponent(Koltuk17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(secim10)
                            .addGap(14, 14, 14)
                            .addComponent(Koltuk1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(secim15)
                            .addGap(15, 15, 15)
                            .addComponent(Koltuk21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(secim20)
                            .addGap(13, 13, 13)
                            .addComponent(Koltuk18))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Koltuk8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Koltuk12)
                                    .addComponent(Koltuk9)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(secim1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(secim2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Koltuk4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(secim6)
                                            .addGap(14, 14, 14)
                                            .addComponent(Koltuk22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(secim11)
                                            .addGap(15, 15, 15)
                                            .addComponent(Koltuk10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(secim16)
                                            .addGap(13, 13, 13)
                                            .addComponent(Koltuk15))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Koltuk3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(secim7)
                                            .addGap(14, 14, 14)
                                            .addComponent(Koltuk23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(secim12)
                                            .addGap(15, 15, 15)
                                            .addComponent(Koltuk6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(secim17)
                                            .addGap(13, 13, 13)
                                            .addComponent(Koltuk13))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(secim4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Koltuk16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(secim9)
                                    .addGap(14, 14, 14)
                                    .addComponent(Koltuk25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(secim14)
                                    .addGap(15, 15, 15)
                                    .addComponent(Koltuk20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(secim19)
                                    .addGap(13, 13, 13)
                                    .addComponent(Koltuk11)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(satır_A)
                        .addGap(57, 57, 57)
                        .addComponent(satır_B)
                        .addGap(57, 57, 57)
                        .addComponent(satır_C)
                        .addGap(58, 58, 58)
                        .addComponent(satır_D)
                        .addGap(56, 56, 56)
                        .addComponent(satır_E)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secim22)
                    .addComponent(secim21)
                    .addComponent(secim23)
                    .addComponent(secim24)
                    .addComponent(secim25))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onayla_but)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(secililer_listesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toplam_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(hata))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        BiletAl bltal = new BiletAl();
        bltal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    // koltuk adedi kontrolü yapar ardından verileri geri göndermek için static string içerisine saklar.
    private void onayla_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onayla_butActionPerformed
        if (secilenbilet_gonder > 4) {
            hata.setVisible(true);
        } else {
            biletleri_gonder = secililer_listesi.getText();
            this.setVisible(false);
            BiletOnay ftr = new BiletOnay();
            ftr.setVisible(true);
        }
    }//GEN-LAST:event_onayla_butActionPerformed


    // checkbox seçimi yapılıp yapılmadığını kontrol eder.
    
    private void secim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim1ActionPerformed
        koltukKontrol();
    }//GEN-LAST:event_secim1ActionPerformed

    private void secim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim2ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim2ActionPerformed

    private void secim3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim3ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim3ActionPerformed

    private void secim4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim4ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim4ActionPerformed

    private void secim5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim5ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim5ActionPerformed

    private void secim6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim6ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim6ActionPerformed

    private void secim7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim7ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim7ActionPerformed

    private void secim8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim8ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim8ActionPerformed

    private void secim9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim9ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim9ActionPerformed

    private void secim10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim10ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim10ActionPerformed

    private void secim11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim11ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim11ActionPerformed

    private void secim12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim12ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim12ActionPerformed

    private void secim13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim13ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim13ActionPerformed

    private void secim14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim14ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim14ActionPerformed

    private void secim15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim15ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim15ActionPerformed

    private void secim16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim16ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim16ActionPerformed

    private void secim17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim17ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim17ActionPerformed

    private void secim18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim18ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim18ActionPerformed

    private void secim19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim19ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim19ActionPerformed

    private void secim20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim20ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim20ActionPerformed

    private void secim21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim21ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim21ActionPerformed

    private void secim22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim22ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim22ActionPerformed

    private void secim23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim23ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim23ActionPerformed

    private void secim24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim24ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim24ActionPerformed

    private void secim25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim25ActionPerformed
        koltukKontrol();        // TODO add your handling code here:
    }//GEN-LAST:event_secim25ActionPerformed

    // daha önce seçilmiş koltukları veritabanı üzerinden alır ve checkboxları kilitler.
    
    public void doluYerler(String film_adi) {
        String tarih = filmtarih;
        String saat = filmsaat;
        String salonadi = filmsalon;
        boolean sonuc = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "A1");
        boolean sonuc1 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "A2");
        boolean sonuc2 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "A3");
        boolean sonuc3 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "A4");
        boolean sonuc4 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "A5");
        boolean sonuc5 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "B1");
        boolean sonuc6 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "B2");
        boolean sonuc7 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "B3");
        boolean sonuc8 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "B4");
        boolean sonuc9 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "B5");
        boolean sonuc10 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "C1");
        boolean sonuc11 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "C2");
        boolean sonuc12 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "C3");
        boolean sonuc13 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "C4");
        boolean sonuc14 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "C5");
        boolean sonuc15 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "D1");
        boolean sonuc16 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "D2");
        boolean sonuc17 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "D3");
        boolean sonuc18 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "D4");
        boolean sonuc19 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "D5");
        boolean sonuc20 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "E1");
        boolean sonuc21 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "E2");
        boolean sonuc22 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "E3");
        boolean sonuc23 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "E4");
        boolean sonuc24 = islemler.koltukDolumu(filmadi, salonadi, tarih, saat, "E5");

        secim1.setSelected(sonuc);
        secim1.setEnabled(!sonuc);
        secim2.setSelected(sonuc1);
        secim2.setEnabled(!sonuc1);
        secim3.setSelected(sonuc2);
        secim3.setEnabled(!sonuc2);
        secim4.setSelected(sonuc3);
        secim4.setEnabled(!sonuc3);
        secim5.setSelected(sonuc4);
        secim5.setEnabled(!sonuc4);
        secim6.setSelected(sonuc5);
        secim6.setEnabled(!sonuc5);
        secim7.setSelected(sonuc6);
        secim7.setEnabled(!sonuc6);
        secim8.setSelected(sonuc7);
        secim8.setEnabled(!sonuc7);
        secim9.setSelected(sonuc8);
        secim9.setEnabled(!sonuc8);
        secim10.setSelected(sonuc9);
        secim10.setEnabled(!sonuc9);
        secim11.setSelected(sonuc10);
        secim11.setEnabled(!sonuc10);
        secim12.setSelected(sonuc11);
        secim12.setEnabled(!sonuc11);
        secim13.setSelected(sonuc12);
        secim13.setEnabled(!sonuc12);
        secim14.setSelected(sonuc13);
        secim14.setEnabled(!sonuc13);
        secim15.setSelected(sonuc14);
        secim15.setEnabled(!sonuc14);
        secim16.setSelected(sonuc15);
        secim16.setEnabled(!sonuc15);
        secim17.setSelected(sonuc16);
        secim17.setEnabled(!sonuc16);
        secim18.setSelected(sonuc17);
        secim18.setEnabled(!sonuc17);
        secim19.setSelected(sonuc18);
        secim19.setEnabled(!sonuc18);
        secim20.setSelected(sonuc19);
        secim20.setEnabled(!sonuc19);
        secim21.setSelected(sonuc20);
        secim21.setEnabled(!sonuc20);
        secim22.setSelected(sonuc21);
        secim22.setEnabled(!sonuc21);
        secim23.setSelected(sonuc22);
        secim23.setEnabled(!sonuc22);
        secim24.setSelected(sonuc23);
        secim24.setEnabled(!sonuc23);
        secim25.setSelected(sonuc24);
        secim25.setEnabled(!sonuc24);

    }

    // seçimi yapılan checkbox ismine göre koltuk bilgisi ve tutar bilgisini günceller.

    public void koltukKontrol() {
        String cvp = "";
        totaltutar_gonder = 0;
        secilenbilet_gonder = 0;
        secililer_listesi.setText(cvp);
        if (secim1.isSelected() && secim1.isEnabled()) {
            cvp += "A1 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;
        }
        if (secim2.isSelected() && secim2.isEnabled()) {
            cvp += "A2 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim3.isSelected() && secim3.isEnabled()) {
            cvp += "A3 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim4.isSelected() && secim4.isEnabled()) {
            cvp += "A4 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim5.isSelected() && secim5.isEnabled()) {
            cvp += "A5 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim6.isSelected() && secim6.isEnabled()) {
            cvp += "B1 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim7.isSelected() && secim7.isEnabled()) {
            cvp += "B2 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim8.isSelected() && secim8.isEnabled()) {
            cvp += "B3 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim9.isSelected() && secim9.isEnabled()) {
            cvp += "B4 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim10.isSelected() && secim10.isEnabled()) {
            cvp += "B5 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim11.isSelected() && secim11.isEnabled()) {
            cvp += "C1 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim12.isSelected() && secim12.isEnabled()) {
            cvp += "C2 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim13.isSelected() && secim13.isEnabled()) {
            cvp += "C3 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim14.isSelected() && secim14.isEnabled()) {
            cvp += "C4 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim15.isSelected() && secim15.isEnabled()) {
            cvp += "C5 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim16.isSelected() && secim16.isEnabled()) {
            cvp += "D1 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim17.isSelected() && secim17.isEnabled()) {
            cvp += "D2 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim18.isSelected() && secim18.isEnabled()) {
            cvp += "D3 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim19.isSelected() && secim19.isEnabled()) {
            cvp += "D4 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim20.isSelected() && secim20.isEnabled()) {
            cvp += "D5 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim21.isSelected() && secim21.isEnabled()) {
            cvp += "E1 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim22.isSelected() && secim22.isEnabled()) {
            cvp += "E2 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim23.isSelected() && secim23.isEnabled()) {
            cvp += "E3 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim24.isSelected() && secim24.isEnabled()) {
            cvp += "E4 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        if (secim25.isSelected() && secim25.isEnabled()) {
            cvp += "E5 ";
            totaltutar_gonder += biletUcret;
            secilenbilet_gonder += 1;

        }
        secililer_listesi.setText(cvp);
        toplam_tutar.setText(String.valueOf(totaltutar_gonder) + " TL");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KoltukSecim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KoltukSecim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KoltukSecim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KoltukSecim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KoltukSecim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Koltuk1;
    private javax.swing.JLabel Koltuk10;
    private javax.swing.JLabel Koltuk11;
    private javax.swing.JLabel Koltuk12;
    private javax.swing.JLabel Koltuk13;
    private javax.swing.JLabel Koltuk14;
    private javax.swing.JLabel Koltuk15;
    private javax.swing.JLabel Koltuk16;
    private javax.swing.JLabel Koltuk17;
    private javax.swing.JLabel Koltuk18;
    private javax.swing.JLabel Koltuk19;
    private javax.swing.JLabel Koltuk2;
    private javax.swing.JLabel Koltuk20;
    private javax.swing.JLabel Koltuk21;
    private javax.swing.JLabel Koltuk22;
    private javax.swing.JLabel Koltuk23;
    private javax.swing.JLabel Koltuk24;
    private javax.swing.JLabel Koltuk25;
    private javax.swing.JLabel Koltuk3;
    private javax.swing.JLabel Koltuk4;
    private javax.swing.JLabel Koltuk5;
    private javax.swing.JLabel Koltuk6;
    private javax.swing.JLabel Koltuk7;
    private javax.swing.JLabel Koltuk8;
    private javax.swing.JLabel Koltuk9;
    private javax.swing.JLabel hata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton onayla_but;
    private javax.swing.JLabel satır_A;
    private javax.swing.JLabel satır_B;
    private javax.swing.JLabel satır_C;
    private javax.swing.JLabel satır_D;
    private javax.swing.JLabel satır_E;
    private javax.swing.JTextField secililer_listesi;
    private javax.swing.JCheckBox secim1;
    private javax.swing.JCheckBox secim10;
    private javax.swing.JCheckBox secim11;
    private javax.swing.JCheckBox secim12;
    private javax.swing.JCheckBox secim13;
    private javax.swing.JCheckBox secim14;
    private javax.swing.JCheckBox secim15;
    private javax.swing.JCheckBox secim16;
    private javax.swing.JCheckBox secim17;
    private javax.swing.JCheckBox secim18;
    private javax.swing.JCheckBox secim19;
    private javax.swing.JCheckBox secim2;
    private javax.swing.JCheckBox secim20;
    private javax.swing.JCheckBox secim21;
    private javax.swing.JCheckBox secim22;
    private javax.swing.JCheckBox secim23;
    private javax.swing.JCheckBox secim24;
    private javax.swing.JCheckBox secim25;
    private javax.swing.JCheckBox secim3;
    private javax.swing.JCheckBox secim4;
    private javax.swing.JCheckBox secim5;
    private javax.swing.JCheckBox secim6;
    private javax.swing.JCheckBox secim7;
    private javax.swing.JCheckBox secim8;
    private javax.swing.JCheckBox secim9;
    private javax.swing.JLabel sutun_1;
    private javax.swing.JLabel sutun_2;
    private javax.swing.JLabel sutun_3;
    private javax.swing.JLabel sutun_4;
    private javax.swing.JLabel sutun_5;
    private javax.swing.JTextField toplam_tutar;
    // End of variables declaration//GEN-END:variables
}
