package com.sinema;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Muratcan Öksüm & Emir Tuncer
 */
public class YetkiliPanel extends javax.swing.JFrame {

    YetkiliGiris ytkg = new YetkiliGiris();
    VeritabaniIslemler islemler = new VeritabaniIslemler();
    private String yetkili_adi = ytkg.yetkili_adi_gonder.toUpperCase();

    /**
     * Creates new form YetkiliPanel
     */
    public YetkiliPanel() {
        initComponents();
        yetkili_olarak.setText("   " + yetkili_adi + " OLARAK OTURUM AÇTINIZ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yetkili_olarak = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        film_yonetim = new javax.swing.JPanel();
        film_yonetim_text = new javax.swing.JLabel();
        bilet_yonetim = new javax.swing.JPanel();
        bilet_yonetimi_text = new javax.swing.JLabel();
        admin_ekle = new javax.swing.JPanel();
        admin_ekle_text = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Yetkili Paneli");
        setIconImage(new ImageIcon("./src/com/sinema/images/icon.png").getImage());
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        yetkili_olarak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yetkili_olarak.setForeground(new java.awt.Color(204, 0, 51));
        yetkili_olarak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yetkili_olarak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/yekilig.png"))); // NOI18N
        yetkili_olarak.setText("   YETKİLİ OLARAK OTURUM AÇTINIZ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/sinema_giris.png"))); // NOI18N

        film_yonetim.setBackground(new java.awt.Color(204, 204, 204));

        film_yonetim_text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        film_yonetim_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        film_yonetim_text.setText("FİLM YÖNETİMİ");
        film_yonetim_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film_yonetim_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film_yonetim_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film_yonetim_textMouseExited(evt);
            }
        });

        javax.swing.GroupLayout film_yonetimLayout = new javax.swing.GroupLayout(film_yonetim);
        film_yonetim.setLayout(film_yonetimLayout);
        film_yonetimLayout.setHorizontalGroup(
            film_yonetimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(film_yonetimLayout.createSequentialGroup()
                .addComponent(film_yonetim_text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        film_yonetimLayout.setVerticalGroup(
            film_yonetimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(film_yonetimLayout.createSequentialGroup()
                .addComponent(film_yonetim_text, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bilet_yonetim.setBackground(new java.awt.Color(204, 204, 204));

        bilet_yonetimi_text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bilet_yonetimi_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bilet_yonetimi_text.setText("BİLET YÖNETİMİ");
        bilet_yonetimi_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bilet_yonetimi_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bilet_yonetimi_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bilet_yonetimi_textMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bilet_yonetimLayout = new javax.swing.GroupLayout(bilet_yonetim);
        bilet_yonetim.setLayout(bilet_yonetimLayout);
        bilet_yonetimLayout.setHorizontalGroup(
            bilet_yonetimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bilet_yonetimi_text, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        bilet_yonetimLayout.setVerticalGroup(
            bilet_yonetimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bilet_yonetimi_text, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        admin_ekle.setBackground(new java.awt.Color(204, 204, 204));
        admin_ekle.setFocusCycleRoot(true);

        admin_ekle_text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        admin_ekle_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin_ekle_text.setText("YETKİLİ EKLE");
        admin_ekle_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_ekle_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admin_ekle_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admin_ekle_textMouseExited(evt);
            }
        });

        javax.swing.GroupLayout admin_ekleLayout = new javax.swing.GroupLayout(admin_ekle);
        admin_ekle.setLayout(admin_ekleLayout);
        admin_ekleLayout.setHorizontalGroup(
            admin_ekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin_ekle_text, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        admin_ekleLayout.setVerticalGroup(
            admin_ekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin_ekle_text, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jMenu1.setText("Seçenekler");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/exit.png"))); // NOI18N
        jMenuItem1.setText("Çıkış");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yetkili_olarak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bilet_yonetim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(film_yonetim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admin_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yetkili_olarak)
                .addGap(27, 27, 27)
                .addComponent(film_yonetim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bilet_yonetim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admin_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed
// buton efekti
    
    private void film_yonetim_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film_yonetim_textMouseEntered
        film_yonetim.setBackground(new java.awt.Color(158, 158, 158));
    }//GEN-LAST:event_film_yonetim_textMouseEntered
// buton efekti

    private void film_yonetim_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film_yonetim_textMouseExited
        film_yonetim.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_film_yonetim_textMouseExited

    // FilmYönetim sayfasını açar. 
    private void film_yonetim_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film_yonetim_textMouseClicked
        film_yonetim.setBackground(new java.awt.Color(170, 170, 170));
        FilmYonetim flm = new FilmYonetim();
        this.setVisible(false);
        flm.setVisible(true);
    }//GEN-LAST:event_film_yonetim_textMouseClicked

    // biletyönetim sayfasını açar
    private void bilet_yonetimi_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_yonetimi_textMouseClicked
        bilet_yonetim.setBackground(new java.awt.Color(170, 170, 170));
        BiletYonetim flm = new BiletYonetim();
        this.setVisible(false);
        flm.setVisible(true);    }//GEN-LAST:event_bilet_yonetimi_textMouseClicked
// buton efekti

    private void bilet_yonetimi_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_yonetimi_textMouseEntered
        bilet_yonetim.setBackground(new java.awt.Color(158, 158, 158));
    }//GEN-LAST:event_bilet_yonetimi_textMouseEntered
// buton efekti

    private void bilet_yonetimi_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilet_yonetimi_textMouseExited
        bilet_yonetim.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_bilet_yonetimi_textMouseExited

    //super yetkili kontrolü yapar ona göre giriş yapar veya text değiştirip feedback verir.
    private void admin_ekle_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_ekle_textMouseClicked
        admin_ekle.setBackground(new java.awt.Color(170, 170, 170));

        if (superYetkilimi()) {
            YetkiliEkle flm = new YetkiliEkle();
            this.setVisible(false);
            flm.setVisible(true);
        } else {
            admin_ekle_text.setForeground(new java.awt.Color(153, 0, 0));
            admin_ekle_text.setText("YETERSİZ YETKİ");
        }
    }//GEN-LAST:event_admin_ekle_textMouseClicked
// buton efekti

    private void admin_ekle_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_ekle_textMouseEntered
        admin_ekle.setBackground(new java.awt.Color(158, 158, 158));
    }//GEN-LAST:event_admin_ekle_textMouseEntered
// buton efekti

    private void admin_ekle_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_ekle_textMouseExited
        admin_ekle.setBackground(new java.awt.Color(204, 204, 204));
        admin_ekle_text.setForeground(Color.black);
        admin_ekle_text.setText("YETKİLİ EKLE");
    }//GEN-LAST:event_admin_ekle_textMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        AnaSayfa ansyf = new AnaSayfa();
        ansyf.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
// superyetkilinin adını veritabanından alır
    public boolean superYetkilimi() {
        if (yetkili_adi.equalsIgnoreCase("admin")) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YetkiliPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YetkiliPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YetkiliPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YetkiliPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YetkiliPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_ekle;
    private javax.swing.JLabel admin_ekle_text;
    private javax.swing.JPanel bilet_yonetim;
    private javax.swing.JLabel bilet_yonetimi_text;
    private javax.swing.JPanel film_yonetim;
    private javax.swing.JLabel film_yonetim_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel yetkili_olarak;
    // End of variables declaration//GEN-END:variables
}
