package com.sinema;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

// FİLM EKLEME SİSTEMİ İLE AYNI ÇOĞALTILMIŞ CLASS

// Yetkili girişi yapabilmeleri hesap oluşturma ekranı ve sadece super yetkili erişim sağlayabilir.

/**
 *
 * @author Muratcan Öksüm & Emir Tuncer
 */
public class YetkiliEkle extends javax.swing.JFrame {

    DefaultTableModel model;
    VeritabaniIslemler islemler = new VeritabaniIslemler();

    public YetkiliEkle() {
        initComponents();
        model = (DefaultTableModel) admin_tablosu.getModel();
        listeGoruntule();
        hata.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        admin_tablosu = new javax.swing.JTable();
        yetkili_adi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yetkili_ekle = new javax.swing.JButton();
        yetkili_guncelle = new javax.swing.JButton();
        yetkili_sil = new javax.swing.JButton();
        hata_mesaj = new javax.swing.JLabel();
        liste_guncelle = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        hata_mesaj2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        hata = new javax.swing.JLabel();
        yetkili_sifre = new javax.swing.JTextField();
        yetkili_kimlik = new javax.swing.JTextField();
        yetkili_dogum = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        exit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Yetkili Yönetim");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon("./src/com/sinema/images/icon.png").getImage());
        setLocation(new java.awt.Point(500, 150));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        admin_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kullanıcı Adı", "Şifre", "Kimlik", "Doğum Yeri"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        admin_tablosu.getTableHeader().setReorderingAllowed(false);
        admin_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(admin_tablosu);
        if (admin_tablosu.getColumnModel().getColumnCount() > 0) {
            admin_tablosu.getColumnModel().getColumn(0).setResizable(false);
            admin_tablosu.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jLabel1.setText("Kullancı Adı :");

        jLabel2.setText("Kimlik No :");

        jLabel3.setText("Doğum Yeri :");

        jLabel4.setText("Şifre :");

        yetkili_ekle.setText("Yetkili Ekle");
        yetkili_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yetkili_ekleActionPerformed(evt);
            }
        });

        yetkili_guncelle.setText("Yetkili Güncelle");
        yetkili_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yetkili_guncelleActionPerformed(evt);
            }
        });

        yetkili_sil.setText("Yetkili Sil");
        yetkili_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yetkili_silActionPerformed(evt);
            }
        });

        hata_mesaj.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        hata_mesaj.setForeground(new java.awt.Color(255, 0, 0));

        liste_guncelle.setText("Liste Güncelle");
        liste_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liste_guncelleActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("YETKİLİ YÖNETİM");
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        hata.setText("123");
        hata.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        hata.setForeground(new java.awt.Color(255, 0, 0));

        exit.setText("Seçenekler");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/exit.png"))); // NOI18N
        jMenuItem1.setText("Çıkış");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        exit.add(jMenuItem1);

        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hata_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yetkili_dogum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yetkili_kimlik, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yetkili_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yetkili_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yetkili_guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yetkili_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yetkili_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(hata, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(liste_guncelle))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(hata_mesaj2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yetkili_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(yetkili_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(yetkili_kimlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(yetkili_dogum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yetkili_ekle)
                        .addGap(10, 10, 10)
                        .addComponent(yetkili_guncelle)
                        .addGap(10, 10, 10)
                        .addComponent(yetkili_sil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hata_mesaj2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hata_mesaj))
                    .addComponent(liste_guncelle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yetkili_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yetkili_guncelleActionPerformed
        String ad = yetkili_adi.getText();
        String sifre = yetkili_sifre.getText();
        String kimlik = yetkili_kimlik.getText();
        String dogum = yetkili_dogum.getText();

        int selectedrow = admin_tablosu.getSelectedRow();

        if (selectedrow == -1) {

            if (model.getRowCount() == 0) {
                hata.setText("Yetkili Tablosu şu anda boş. ");
            } else {
                hata.setText("Lütfen güncellenecek bir yetkili seçin.");
            }
        } else {

            int id = (int) model.getValueAt(selectedrow, 0);
            islemler.yetkiliGuncelle(id, ad, sifre, kimlik, dogum);

            listeGoruntule();
            hata.setText("Yetkili başarıyla güncellendi...");
        }


    }//GEN-LAST:event_yetkili_guncelleActionPerformed

    private void yetkili_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yetkili_silActionPerformed
        hata.setText("");

        int selectedrow = admin_tablosu.getSelectedRow();
        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                hata.setText("Yetkili tablosu şu anda boş...");
            } else {
                hata.setText("Lütfen silinecek bir yetkili seçin...");
            }

        } else {
            int id = (int) model.getValueAt(selectedrow, 0);
            islemler.yetkiliSil(id);
            listeGoruntule();
            temizleVeri();
            hata.setText("Yetkili başarıyla silindi...");
        }
    }//GEN-LAST:event_yetkili_silActionPerformed

    private void yetkili_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yetkili_ekleActionPerformed
        hata.setText("");

        String ad = yetkili_adi.getText();
        String sifre = yetkili_sifre.getText();
        String kimlik = yetkili_kimlik.getText();
        String dogum = yetkili_dogum.getText();

        islemler.yetkiliEkle(ad, sifre, kimlik, dogum);
        listeGoruntule();
        yetkili_adi.setText("");
        yetkili_sifre.setText("");
        yetkili_kimlik.setText("");
        yetkili_dogum.setText("");
        temizleVeri();
        hata.setText("Yeni Yetkili Başarıyla Eklendi...");
    }//GEN-LAST:event_yetkili_ekleActionPerformed

    private void liste_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liste_guncelleActionPerformed
        listeGoruntule();
        hata.setText("Liste Güncellendi ...");
    }//GEN-LAST:event_liste_guncelleActionPerformed

    private void admin_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_tablosuMouseClicked
        int selectedrow = admin_tablosu.getSelectedRow();

        yetkili_adi.setText(model.getValueAt(selectedrow, 1).toString());
        yetkili_sifre.setText((model.getValueAt(selectedrow, 2).toString()));
        yetkili_kimlik.setText(model.getValueAt(selectedrow, 3).toString());
        yetkili_dogum.setText(model.getValueAt(selectedrow, 4).toString());
    }//GEN-LAST:event_admin_tablosuMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        YetkiliPanel ansyf = new YetkiliPanel();
        ansyf.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    public void listeGoruntule() {

        model.setRowCount(0);

        ArrayList<Yetkili> yetkililer = new ArrayList<Yetkili>();

        yetkililer = islemler.yetkiliGetir();

        if (yetkililer != null) {

            for (Yetkili yetki : yetkililer) {
                Object[] eklenecek = {yetki.getId(), yetki.getAd(), yetki.getPassword(), yetki.getKimlik(), yetki.getDogum()};

                model.addRow(eklenecek);

            }

        }

    }

    public void temizleVeri() {
        yetkili_adi.setText("");
        yetkili_sifre.setText("");
        yetkili_dogum.setText("");
        yetkili_kimlik.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YetkiliEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YetkiliEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YetkiliEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YetkiliEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YetkiliEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable admin_tablosu;
    private javax.swing.JMenu exit;
    private javax.swing.JLabel hata;
    private javax.swing.JLabel hata_mesaj;
    private javax.swing.JLabel hata_mesaj2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton liste_guncelle;
    private javax.swing.JTextField yetkili_adi;
    private javax.swing.JTextField yetkili_dogum;
    private javax.swing.JButton yetkili_ekle;
    private javax.swing.JButton yetkili_guncelle;
    private javax.swing.JTextField yetkili_kimlik;
    private javax.swing.JTextField yetkili_sifre;
    private javax.swing.JButton yetkili_sil;
    // End of variables declaration//GEN-END:variables
}
