package com.sinema;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Muratcan Öksüm & Emir Tuncer
 */
public class YetkiliGiris extends javax.swing.JFrame {

    VeritabaniIslemler islemler = new VeritabaniIslemler();
    public static String yetkili_adi_gonder = "";

    /**
     * Creates new form Yetkili
     */
    public YetkiliGiris() {
        initComponents();
        veri_sifirla.setVisible(false);
        veri_onayla.setVisible(false);
        sifirla_text.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        kullanici_adi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        hata_mesaj = new javax.swing.JLabel();
        sifirla_text = new javax.swing.JLabel();
        veri_sifirla = new javax.swing.JPasswordField();
        veri_onayla = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        veritabani_si = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Yetkili Giriş");
        setIconImage(new ImageIcon("./src/com/sinema/images/icon.png").getImage());
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Users\\Documents\\NetBeansProjects\\SinemaOtomasyonu\\src\\com\\sinema\\images\\yekilis_giris2.png")); // NOI18N

        jLabel1.setText("Kullanıcı Adı:");

        jLabel3.setText("Parola:");

        jButton1.setText("Giriş Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Şifre Unuttum");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        hata_mesaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hata_mesaj.setForeground(new java.awt.Color(204, 0, 0));
        hata_mesaj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        sifirla_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sifirla_text.setForeground(new java.awt.Color(204, 0, 0));
        sifirla_text.setText("Sıfırlama Şifresi :");

        veri_onayla.setText("Onayla");
        veri_onayla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veri_onaylaActionPerformed(evt);
            }
        });

        jMenu1.setText("Seçenekler");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/yetkili.png"))); // NOI18N
        jMenuItem2.setText("Ana Menü");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sinema/images/exit.png"))); // NOI18N
        jMenuItem1.setText("Çıkış");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        veritabani_si.setText("Veri Tabanı Sıfırla");
        veritabani_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veritabani_siActionPerformed(evt);
            }
        });
        jMenu1.add(veritabani_si);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(kullanici_adi)
                                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(hata_mesaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(sifirla_text)
                        .addGap(18, 18, 18)
                        .addComponent(veri_sifirla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(veri_onayla)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hata_mesaj)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifirla_text)
                    .addComponent(veri_sifirla)
                    .addComponent(veri_onayla))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        AnaSayfa ansyf = new AnaSayfa();
        ansyf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // veritabanı içerisindeki kullanıcı bilgilerini kontrol eder ve doğru ise yetkilipaneli classı üzerinden 
    // panel görünümünü açar.
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        hata_mesaj.setText("");

        String kullanici_adi = this.kullanici_adi.getText();
        String parola = new String(password.getPassword());
        yetkili_adi_gonder = kullanici_adi;
        boolean girisbasarili = islemler.girisYap(kullanici_adi, parola);

        if (girisbasarili) {
            YetkiliPanel yetkiliEkrani = new YetkiliPanel();
            setVisible(false);
            yetkiliEkrani.setVisible(true);
        } else {
            hata_mesaj.setText("Giriş Başarısız...Lütfen tekrar deneyin.");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SifreUnut sfrt = new SifreUnut();
        sfrt.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        AnaSayfa ansyf = new AnaSayfa();
        ansyf.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    // password textfield içerisinde "ENTER" tuşuna bastığımızda 
    // jButton1ActionPerformed fonksiyonu ile aynı işlevi yapar.
    
    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            hata_mesaj.setText("");

            String kullanici_adi = this.kullanici_adi.getText();
            String parola = new String(password.getPassword());
            yetkili_adi_gonder = kullanici_adi;
            boolean girisbasarili = islemler.girisYap(kullanici_adi, parola);

            if (girisbasarili) {
                YetkiliPanel yetkiliEkrani = new YetkiliPanel();
                setVisible(false);
                yetkiliEkrani.setVisible(true);
            } else {
                hata_mesaj.setText("Giriş Başarısız...Lütfen tekrar deneyin.");

            }
        }
    }//GEN-LAST:event_passwordKeyPressed

    // şifre sıfırlamak için daha önce belirlenmiş Database içerisinde saklanan static final string
    // değerini kontrol eder doğru ise mysql veritabını içerisindeki tüm tabloları silip yenilerini açar.
    
    private void veri_onaylaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veri_onaylaActionPerformed
        String sifre = new String(veri_sifirla.getPassword());
        if (sifre.equals(Database.sifirlasifre)) {
            veri_sifirla.setVisible(false);
            veri_onayla.setVisible(false);
            sifirla_text.setVisible(false);
            veri_sifirla.setText("");
            islemler.veritabaniSifirla();
            JOptionPane.showMessageDialog(null, "Veritabanı sıfırlama işlemi başarıyla tamamlandı.", "Veritabanı Sıfırlama Sistemi", 1);
        } else {
            veri_sifirla.setText("");
            JOptionPane.showMessageDialog(null, "Veritabanı sıfırlama şifreniz  yanlış", "Veritabanı Sıfırlama Sistemi", 1);
        }

    }//GEN-LAST:event_veri_onaylaActionPerformed

    // yetkili için gerekli olan şifre bölümünü görünür kılar. 
    
    private void veritabani_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veritabani_siActionPerformed
        veri_sifirla.setVisible(true);
        veri_onayla.setVisible(true);
        sifirla_text.setVisible(true);
    }//GEN-LAST:event_veritabani_siActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YetkiliGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YetkiliGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YetkiliGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YetkiliGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YetkiliGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hata_mesaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel sifirla_text;
    private javax.swing.JButton veri_onayla;
    private javax.swing.JPasswordField veri_sifirla;
    private javax.swing.JMenuItem veritabani_si;
    // End of variables declaration//GEN-END:variables
}
